#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute
homepage:
    path: /
    controller: App\Controller\FirstController::index
contact:
    path: /contact
    controller : App\Controller\FirstController::form
my_json:
    path: /json
    controller: App\Control
 